### ISSUE TITLE
Add Skills to User Profile

### ISSUE THREAD

**Issue by DominicWebDev** [DominicWebDev/capstone-meinitjob-frontend#1]
# Add Skills to User Profile

## Value Proposition

As a user, I want to be able to add my skills to my profile.

## Acceptance Criteria

- [ ] The user can view and edit a list of skills in their profile.
- [ ] Skills are saved and displayed accurately on the user's profile.

## Tasks

- [ ] Implement a UI that allows users to add and remove skills from their profile.
