### ISSUE TITLE
UserLogIn

### ISSUE THREAD

**Issue by DominicWebDev** [DominicWebDev/capstone-meinitjob-frontend#12]
## Value Proposition:

As a user, I want to be able to log in to my account using my GitHub credentials through Next Auth, so that I can easily access my account and not have to remember another set of login credentials.

## Acceptance Criteria:

 - [ ] The user can click on the GitHub login button on the login page.
  - [ ] The user is redirected to GitHub to authenticate their account.
  - [ ] After successful authentication, the user is redirected back to the website and logged in to their account.

 
## Tasks:

  - [ ] Add a GitHub login button to the login page.
