### ISSUE TITLE
Add Personal Information to User Profile

### ISSUE THREAD

**Issue by DominicWebDev** [DominicWebDev/capstone-meinitjob-frontend#2]
## Value Proposition

As a user, I want to be able to add my personal information to my profile.

## Acceptance Criteria

- [ ] The user can view and edit their personal information in their profile.
- [ ] Personal information is saved and displayed accurately on the user's profile.

## Tasks

- [ ] Design a UI for displaying and adding personal information to a user's profile.
- [ ] Implement a UI that allows users to add and edit their personal information on their 
       profile.
