### ISSUE TITLE
Set Availability for Full-time or Part-time Work

### ISSUE THREAD

**Issue by DominicWebDev** [DominicWebDev/capstone-meinitjob-frontend#3]
## Value Proposition

As a user, I want to be able to set my availability for full-time or part-time work.

## Acceptance Criteria

- [ ] The user can select their availability for full-time or part-time work in their profile.
- [ ] The user's availability is saved and displayed accurately on their profile.

## Tasks

- [ ] Design a UI for selecting and displaying a user's availability for full-time or part-time 
       work.

- [ ]  Implement a UI that allows users to set their availability for full-time or part-time 
        work.
- [ ]  Refine the UI and functionality based on user feedback.
