### ISSUE TITLE
Set Remote Work Preference

### ISSUE THREAD

**Issue by DominicWebDev** [DominicWebDev/capstone-meinitjob-frontend#4]
## Value Proposition

As a user, I want to be able to specify my preference for remote work.

## Acceptance Criteria

- [ ] The user can select their preference for remote work in their profile.
- [ ] The selected remote work preference is saved and displayed accurately on their 
        profile.
 
## Tasks

- [ ] Design a UI for selecting and displaying a user's remote work preference.
- [ ] Implement a UI that allows users to set their remote work preference.
