### ISSUE TITLE
NavBar

### ISSUE THREAD

**Issue by DominicWebDev** [DominicWebDev/capstone-meinitjob-frontend#5]
## Value proposition

As a user, 
I want to be able to navigate between the 
routes of the web application using a navigation bar.

## Acceptance criteria

- [x] The navigation bar should be displayed on all pages.
- [x] All navigation bar links must be clickable.
- [x] Clicking on a navigation bar link must redirect to the intended page.

## Tasks

- [x] Add a navigation bar component to the web application.
- [x] Ensure that the navigation bar component is displayed on all pages.
- [x] Implement clickable navigation bar links that redirect to their intended pages.
- [x] Test the navigation bar to verify that all links are working correctly.
- [x] Ensure that the navigation bar component is responsive and works well on different screen sizes.

**Comment by augustinanders** [comment]
LGTM!🙌
