### ISSUE TITLE
UserProfile

### ISSUE THREAD

**Issue by DominicWebDev** [DominicWebDev/capstone-meinitjob-frontend#7]

**Comment by DominicWebDev** [comment]
# Add Informations to User Profile


## Value Proposition

As a user, I want to be able to add my skills, preferences and personal information to my profile.

## Acceptance Criteria

- [x] The user can view and edit a list of skills in their profile.
- [x] Skills are saved and displayed accurately on the user's profile.
- [x] The user can view and edit their personal information in their profile.
- [x] Personal information is saved and displayed accurately on the user's profile.
- [x] The user can select their availability for full-time or part-time work in their profile.
- [x] The user can select their preference for remote work in their profile.

## Tasks

- [x] Implement a UI that allows users to add and remove information from their profile.

**Comment by augustinanders** [comment]
Looks good to me! maybe you can split it up into a `Form` US and a `Profile Page` US.

**Comment by augustinanders** [comment]
Also would be nice to have some wireframes in the UserStories.
