### ISSUE TITLE
MatchingFunction

### ISSUE THREAD

**Issue by DominicWebDev** [DominicWebDev/capstone-meinitjob-frontend#8]
# Swiping Suggested Companies

## Value Proposition

As a user, I want to swipe suggested companies right (accept) or left (reject)

## Acceptance Criteria

 - [ ] Display suggested companies one at a time.
  - [ ] Allow swiping right to accept and left to reject the displayed company.
 - [ ]  Only display companies that have interest in the skills the user has.

## Tasks

 - [ ]  Create a SuggestedCompanies component that fetches and displays one company at a time.
  - [ ] Implement swipe functionality for accepting or rejecting companies.
  - [ ] Filter the displayed companies based on their interest in the user.

**Comment by rabe200** [comment]
lgtm, i am very interested into the swiping. looking forward for your project! :)
